version: "3"

services:
  audio_extractor:
    build: .
    environment:
      QUEUE_SERVER: "localhost:5672"
      INPUT_QUEUE_NAME: "ae-in"
      OUTPUT_QUEUE_NAME: "ae-out"
      FILES_SERVER: "http://localhost:3001"
    depends_on:
      - rabbitmq