version: "3"

services:
  audio_extractor:
    build: .
    environment:
      QUEUE_SERVER: "localhost:5672"
      FILES_SERVER: "localhost:3001"
      INPUT_QUEUE_NAME: "audio_extractor_in"
      OUTPUT_QUEUE_NAME: "audio_extractor_out"